INSERT INTO AnswerCards(id,text) VALUES (1,'Vigorous jazz hands.');
INSERT INTO AnswerCards(id,text) VALUES (2,'Flightless birds.');
INSERT INTO AnswerCards(id,text) VALUES (3,'Doing the right thing.');
INSERT INTO AnswerCards(id,text) VALUES (4,'Self-loathing.');
INSERT INTO AnswerCards(id,text) VALUES (5,'Spectacular abs.');
INSERT INTO AnswerCards(id,text) VALUES (6,'A balanced breakfast.');
INSERT INTO AnswerCards(id,text) VALUES (7,'The Big Bang.');
INSERT INTO AnswerCards(id,text) VALUES (8,'Cuddling.');
INSERT INTO AnswerCards(id,text) VALUES (9,'Laying an egg.');
INSERT INTO AnswerCards(id,text) VALUES (10,'The Pope.');
INSERT INTO AnswerCards(id,text) VALUES (11,'Aaron Burr.');
INSERT INTO AnswerCards(id,text) VALUES (12,'Horse meat.');
INSERT INTO AnswerCards(id,text) VALUES (13,'Fear itself.');
INSERT INTO AnswerCards(id,text) VALUES (14,'Science.');
INSERT INTO AnswerCards(id,text) VALUES (15,'Making a pouty face.');
INSERT INTO AnswerCards(id,text) VALUES (16,'William Shatner.');
INSERT INTO AnswerCards(id,text) VALUES (17,'Nickelback.');
INSERT INTO AnswerCards(id,text) VALUES (18,'Tom Cruise.');
INSERT INTO AnswerCards(id,text) VALUES (19,'Chainsaws for hands.');
INSERT INTO AnswerCards(id,text) VALUES (20,'Arnold Schwarzenegger.');
INSERT INTO AnswerCards(id,text) VALUES (21,'Goblins.');
INSERT INTO AnswerCards(id,text) VALUES (22,'Object permanence.');
INSERT INTO AnswerCards(id,text) VALUES (23,'A falcon with a cap on its head.');
INSERT INTO AnswerCards(id,text) VALUES (24,'Dying of dysentery.');
INSERT INTO AnswerCards(id,text) VALUES (25,'A really cool hat.');
INSERT INTO AnswerCards(id,text) VALUES (26,'Sean Penn.');
INSERT INTO AnswerCards(id,text) VALUES (27,'Raptor attacks.');
INSERT INTO AnswerCards(id,text) VALUES (28,'Agriculture.');
INSERT INTO AnswerCards(id,text) VALUES (29,'Vikings.');
INSERT INTO AnswerCards(id,text) VALUES (30,'Pretending to care.');
INSERT INTO AnswerCards(id,text) VALUES (31,'My humps.');
INSERT INTO AnswerCards(id,text) VALUES (32,'Geese.');
INSERT INTO AnswerCards(id,text) VALUES (33,'Bling.');
INSERT INTO AnswerCards(id,text) VALUES (34,'Mutually-assured destruction.');
INSERT INTO AnswerCards(id,text) VALUES (35,'Sunshine and rainbows.');
INSERT INTO AnswerCards(id,text) VALUES (36,'Count Chocula.');
INSERT INTO AnswerCards(id,text) VALUES (37,'Being rich.');
INSERT INTO AnswerCards(id,text) VALUES (38,'Skeletor.');
INSERT INTO AnswerCards(id,text) VALUES (39,'A sausage festival.');
INSERT INTO AnswerCards(id,text) VALUES (40,'Emotions.');
INSERT INTO AnswerCards(id,text) VALUES (41,'Spontaneous human combustion.');
INSERT INTO AnswerCards(id,text) VALUES (42,'Leaving an awkward voicemail.');
INSERT INTO AnswerCards(id,text) VALUES (43,'Teaching a robot to love.');
INSERT INTO AnswerCards(id,text) VALUES (44,'Catapults.');
INSERT INTO AnswerCards(id,text) VALUES (45,'Natural selection.');
INSERT INTO AnswerCards(id,text) VALUES (46,'Opposable thumbs.');
INSERT INTO AnswerCards(id,text) VALUES (47,'Figgy pudding.');
INSERT INTO AnswerCards(id,text) VALUES (48,'Preteens.');
INSERT INTO AnswerCards(id,text) VALUES (49,'Five-Dollar Footlongs&trade;.');
INSERT INTO AnswerCards(id,text) VALUES (50,'Land mines.');
INSERT INTO AnswerCards(id,text) VALUES (51,'A sea of troubles.');
INSERT INTO AnswerCards(id,text) VALUES (52,'A zesty breakfast burrito.');
INSERT INTO AnswerCards(id,text) VALUES (53,'Christopher Walken.');
INSERT INTO AnswerCards(id,text) VALUES (54,'Friction.');
INSERT INTO AnswerCards(id,text) VALUES (55,'A tiny horse.');
INSERT INTO AnswerCards(id,text) VALUES (56,'Authentic Mexican cuisine.');
INSERT INTO AnswerCards(id,text) VALUES (57,'Genghis Khan.');
INSERT INTO AnswerCards(id,text) VALUES (58,'The Tempur-Pedic&reg; Swedish Sleep System&trade;.');
INSERT INTO AnswerCards(id,text) VALUES (59,'A thermonuclear detonation.');
INSERT INTO AnswerCards(id,text) VALUES (60,'Take-backsies.');
INSERT INTO AnswerCards(id,text) VALUES (61,'RoboCop.');
INSERT INTO AnswerCards(id,text) VALUES (62,'Keanu Reeves.');
INSERT INTO AnswerCards(id,text) VALUES (63,'Giving 110%.');
INSERT INTO AnswerCards(id,text) VALUES (64,'Flesh-eating bacteria.');
INSERT INTO AnswerCards(id,text) VALUES (65,'The American Dream.');
INSERT INTO AnswerCards(id,text) VALUES (66,'Me time.');
INSERT INTO AnswerCards(id,text) VALUES (67,'A murder most foul.');
INSERT INTO AnswerCards(id,text) VALUES (68,'That thing that electrocutes your abs.');
INSERT INTO AnswerCards(id,text) VALUES (69,'Cards Against Humanity.');
INSERT INTO AnswerCards(id,text) VALUES (70,'Edible underpants.');
INSERT INTO AnswerCards(id,text) VALUES (71,'All-you-can-eat shrimp for $4.99.');
INSERT INTO AnswerCards(id,text) VALUES (72,'Fancy Feast&reg;.');
INSERT INTO AnswerCards(id,text) VALUES (73,'Ronald Reagan.');
INSERT INTO AnswerCards(id,text) VALUES (74,'Hulk Hogan.');
INSERT INTO AnswerCards(id,text) VALUES (75,'God.');
INSERT INTO AnswerCards(id,text) VALUES (76,'Sean Connery.');
INSERT INTO AnswerCards(id,text) VALUES (77,'Saxophone solos.');
INSERT INTO AnswerCards(id,text) VALUES (78,'The World of Warcraft.');
INSERT INTO AnswerCards(id,text) VALUES (79,'Darth Vader.');
INSERT INTO AnswerCards(id,text) VALUES (80,'Hot Pockets&reg;.');
INSERT INTO AnswerCards(id,text) VALUES (81,'A time travel paradox.');
INSERT INTO AnswerCards(id,text) VALUES (82,'The milk man.');
INSERT INTO AnswerCards(id,text) VALUES (83,'Dropping a chandelier on your enemies and riding the rope up.');
INSERT INTO AnswerCards(id,text) VALUES (84,'World peace.');
INSERT INTO AnswerCards(id,text) VALUES (85,'Licking things to claim them as your own.');
INSERT INTO AnswerCards(id,text) VALUES (86,'A good sniff.');
INSERT INTO AnswerCards(id,text) VALUES (87,'Friendly fire.');
INSERT INTO AnswerCards(id,text) VALUES (88,'Free samples.');
INSERT INTO AnswerCards(id,text) VALUES (89,'Explosions.');
INSERT INTO AnswerCards(id,text) VALUES (90,'Getting really high.');
INSERT INTO AnswerCards(id,text) VALUES (91,'Attitude.');
INSERT INTO AnswerCards(id,text) VALUES (92,'My soul.');
INSERT INTO AnswerCards(id,text) VALUES (93,'Pabst Blue Ribbon.');
INSERT INTO AnswerCards(id,text) VALUES (94,'Domino''s&trade; Oreo&trade; Dessert Pizza.');
INSERT INTO AnswerCards(id,text) VALUES (95,'Bill Nye the Science Guy.');
INSERT INTO AnswerCards(id,text) VALUES (96,'Prancing.');
INSERT INTO AnswerCards(id,text) VALUES (97,'Passing a kidney stone.');
INSERT INTO AnswerCards(id,text) VALUES (98,'Puppies!');
INSERT INTO AnswerCards(id,text) VALUES (99,'Bees?');
INSERT INTO AnswerCards(id,text) VALUES (100,'Frolicking.');
INSERT INTO AnswerCards(id,text) VALUES (101,'Overcompensation.');
INSERT INTO AnswerCards(id,text) VALUES (102,'Riding off into the sunset.');
INSERT INTO AnswerCards(id,text) VALUES (103,'Being on fire.');
INSERT INTO AnswerCards(id,text) VALUES (104,'Tangled Slinkys.');
INSERT INTO AnswerCards(id,text) VALUES (105,'Shaquille O''Neal''s acting career.');
INSERT INTO AnswerCards(id,text) VALUES (106,'Justin Bieber.');
INSERT INTO AnswerCards(id,text) VALUES (107,'The Hamburglar.');
INSERT INTO AnswerCards(id,text) VALUES (108,'Classist undertones.');
INSERT INTO AnswerCards(id,text) VALUES (109,'New Age music.');
INSERT INTO AnswerCards(id,text) VALUES (110,'The Kool-Aid Man.');
INSERT INTO AnswerCards(id,text) VALUES (111,'GoGurt&reg;.');
INSERT INTO AnswerCards(id,text) VALUES (112,'Judge Judy.');
INSERT INTO AnswerCards(id,text) VALUES (113,'BATMAN!!!');
INSERT INTO AnswerCards(id,text) VALUES (114,'A disappointing birthday party.');
INSERT INTO AnswerCards(id,text) VALUES (115,'An M. Night Shyamalan plot twist.');
INSERT INTO AnswerCards(id,text) VALUES (116,'Lunchables&trade;.');
INSERT INTO AnswerCards(id,text) VALUES (117,'John Wilkes Booth.');
INSERT INTO AnswerCards(id,text) VALUES (118,'Powerful thighs.');
INSERT INTO AnswerCards(id,text) VALUES (119,'Mr. Clean, right behind you.');
INSERT INTO AnswerCards(id,text) VALUES (120,'Cybernetic enhancements.');
INSERT INTO AnswerCards(id,text) VALUES (121,'The Dance of the Sugar Plum Fairy.');
INSERT INTO AnswerCards(id,text) VALUES (122,'Parting the Red Sea.');
INSERT INTO AnswerCards(id,text) VALUES (123,'AXE Body Spray.');
INSERT INTO AnswerCards(id,text) VALUES (124,'Centaurs.');
INSERT INTO AnswerCards(id,text) VALUES (125,'Grandma.');
INSERT INTO AnswerCards(id,text) VALUES (126,'Finger painting.');
INSERT INTO AnswerCards(id,text) VALUES (127,'The Force.');
INSERT INTO AnswerCards(id,text) VALUES (128,'Active listening.');
INSERT INTO AnswerCards(id,text) VALUES (129,'Ghosts.');
INSERT INTO AnswerCards(id,text) VALUES (130,'Shapeshifters.');
INSERT INTO AnswerCards(id,text) VALUES (131,'The Care Bear Stare.');
INSERT INTO AnswerCards(id,text) VALUES (132,'Hot cheese.');
INSERT INTO AnswerCards(id,text) VALUES (133,'A Bop It&trade;.');
INSERT INTO AnswerCards(id,text) VALUES (134,'Horrifying laser hair removal accidents.');
INSERT INTO AnswerCards(id,text) VALUES (135,'Boogers.');
INSERT INTO AnswerCards(id,text) VALUES (136,'Unfathomable stupidity.');
INSERT INTO AnswerCards(id,text) VALUES (137,'Breaking out into song and dance.');
INSERT INTO AnswerCards(id,text) VALUES (138,'Soup that is too hot.');
INSERT INTO AnswerCards(id,text) VALUES (139,'The true meaning of Christmas.');
INSERT INTO AnswerCards(id,text) VALUES (140,'My inner demons.');
INSERT INTO AnswerCards(id,text) VALUES (141,'Actually taking candy from a baby.');
INSERT INTO AnswerCards(id,text) VALUES (142,'Exactly what you''d expect.');
INSERT INTO AnswerCards(id,text) VALUES (143,'Passive-aggressive Post-it notes.');
INSERT INTO AnswerCards(id,text) VALUES (144,'Inappropriate yodeling.');
INSERT INTO AnswerCards(id,text) VALUES (145,'Lady Gaga.');
INSERT INTO AnswerCards(id,text) VALUES (146,'The Little Engine That Could.');
INSERT INTO AnswerCards(id,text) VALUES (147,'Vigilante justice.');
INSERT INTO AnswerCards(id,text) VALUES (148,'A death ray.');
INSERT INTO AnswerCards(id,text) VALUES (149,'Poor life choices.');
INSERT INTO AnswerCards(id,text) VALUES (150,'Nicolas Cage.');
INSERT INTO AnswerCards(id,text) VALUES (151,'Switching to Geico&reg;.');
INSERT INTO AnswerCards(id,text) VALUES (152,'A subscription to Men''s Fitness.');
INSERT INTO AnswerCards(id,text) VALUES (153,'A micropig wearing a tiny raincoat and booties.');
INSERT INTO AnswerCards(id,text) VALUES (154,'A tribe of warrior women.');
INSERT INTO AnswerCards(id,text) VALUES (155,'The penny whistle solo from ''My Heart Will Go On.''');
INSERT INTO AnswerCards(id,text) VALUES (156,'An oversized lollipop.');
INSERT INTO AnswerCards(id,text) VALUES (157,'Her Majesty, Queen Elizabeth II.');
INSERT INTO AnswerCards(id,text) VALUES (158,'Funky fresh rhymes.');
INSERT INTO AnswerCards(id,text) VALUES (159,'The art of seduction.');
INSERT INTO AnswerCards(id,text) VALUES (160,'The Devil himself.');
INSERT INTO AnswerCards(id,text) VALUES (161,'Destroying the evidence.');
INSERT INTO AnswerCards(id,text) VALUES (162,'The light of a billion suns.');
INSERT INTO AnswerCards(id,text) VALUES (163,'Synergistic management solutions.');
INSERT INTO AnswerCards(id,text) VALUES (164,'Silence.');
INSERT INTO AnswerCards(id,text) VALUES (165,'A live studio audience.');
INSERT INTO AnswerCards(id,text) VALUES (166,'An uppercut.');
INSERT INTO AnswerCards(id,text) VALUES (167,'Shiny objects.');
INSERT INTO AnswerCards(id,text) VALUES (168,'One trillion dollars.');
INSERT INTO AnswerCards(id,text) VALUES (169,'Gladiatorial combat.');
INSERT INTO AnswerCards(id,text) VALUES (170,'Good grammar.');
INSERT INTO AnswerCards(id,text) VALUES (171,'Hipsters.');
INSERT INTO AnswerCards(id,text) VALUES (172,'Gandalf.');
INSERT INTO AnswerCards(id,text) VALUES (173,'Genetically engineered super-soldiers.');
INSERT INTO AnswerCards(id,text) VALUES (174,'Fabricating statistics.');
INSERT INTO AnswerCards(id,text) VALUES (175,'Finding a skeleton.');
INSERT INTO AnswerCards(id,text) VALUES (176,'Dorito breath.');
INSERT INTO AnswerCards(id,text) VALUES (177,'One thousand Slim Jims.');
INSERT INTO AnswerCards(id,text) VALUES (178,'My machete.');
INSERT INTO AnswerCards(id,text) VALUES (179,'Overpowering your father.');
INSERT INTO AnswerCards(id,text) VALUES (180,'Ominous background music.');
INSERT INTO AnswerCards(id,text) VALUES (181,'Media coverage.');
INSERT INTO AnswerCards(id,text) VALUES (182,'Moral ambiguity.');
INSERT INTO AnswerCards(id,text) VALUES (183,'Medieval Times&reg; Dinner &amp; Tournament.');
INSERT INTO AnswerCards(id,text) VALUES (184,'Mad hacky-sack skills.');
INSERT INTO AnswerCards(id,text) VALUES (185,'Leveling up.');
INSERT INTO AnswerCards(id,text) VALUES (186,'Jafar.');
INSERT INTO AnswerCards(id,text) VALUES (187,'Slow motion.');
INSERT INTO AnswerCards(id,text) VALUES (188,'Space muffins.');
INSERT INTO AnswerCards(id,text) VALUES (189,'Santa Claus.');
INSERT INTO AnswerCards(id,text) VALUES (190,'Ryan Gosling riding in on a white horse.');
INSERT INTO AnswerCards(id,text) VALUES (191,'Quiche.');
INSERT INTO AnswerCards(id,text) VALUES (192,'Being a busy adult with many important things to do.');
INSERT INTO AnswerCards(id,text) VALUES (193,'A rival dojo.');
INSERT INTO AnswerCards(id,text) VALUES (194,'Clams.');
INSERT INTO AnswerCards(id,text) VALUES (195,'Spring break!');
INSERT INTO AnswerCards(id,text) VALUES (196,'The Google.');
INSERT INTO AnswerCards(id,text) VALUES (197,'Special musical guest, Cher.');
INSERT INTO AnswerCards(id,text) VALUES (198,'My first kill.');
INSERT INTO AnswerCards(id,text) VALUES (199,'The mere concept of Applebee''s&reg;.');
INSERT INTO AnswerCards(id,text) VALUES (200,'Weapons-grade plutonium.');
INSERT INTO AnswerCards(id,text) VALUES (201,'Loki, the trickster god.');
INSERT INTO AnswerCards(id,text) VALUES (202,'An unhinged ferris wheel rolling toward the sea.');
INSERT INTO AnswerCards(id,text) VALUES (203,'Finding Waldo.');
INSERT INTO AnswerCards(id,text) VALUES (204,'Me.');
INSERT INTO AnswerCards(id,text) VALUES (205,'Some kind of bird-man.');
INSERT INTO AnswerCards(id,text) VALUES (206,'Going around punching people.');
INSERT INTO AnswerCards(id,text) VALUES (207,'A boo-boo.');
INSERT INTO AnswerCards(id,text) VALUES (208,'Indescribable loneliness.');
INSERT INTO AnswerCards(id,text) VALUES (209,'Chugging a lava lamp.');
INSERT INTO AnswerCards(id,text) VALUES (210,'The Land of Chocolate.');
INSERT INTO AnswerCards(id,text) VALUES (211,'Mufasa''s death scene.');
INSERT INTO AnswerCards(id,text) VALUES (212,'The Harlem Globetrotters.');
INSERT INTO AnswerCards(id,text) VALUES (213,'Demonic possession.');
INSERT INTO AnswerCards(id,text) VALUES (214,'Drinking ten 5-hour ENERGYs&reg; to get fifty continuous hours of energy.');
INSERT INTO AnswerCards(id,text) VALUES (215,'Putting an entire peanut butter and jelly sandwich into the VCR.');
INSERT INTO AnswerCards(id,text) VALUES (216,'An unstoppable wave of fire ants.');
INSERT INTO AnswerCards(id,text) VALUES (217,'A greased-up Matthew McConaughey.');
INSERT INTO AnswerCards(id,text) VALUES (218,'Unlimited soup, salad, and breadsticks.');
INSERT INTO AnswerCards(id,text) VALUES (219,'Not contributing to society in any meaningful way.');
INSERT INTO AnswerCards(id,text) VALUES (220,'Velcro&trade;.');
INSERT INTO AnswerCards(id,text) VALUES (221,'A PowerPoint presentation.');
INSERT INTO AnswerCards(id,text) VALUES (222,'Moderate-to-severe joint pain.');
