INSERT INTO question_cards(id,text) VALUES (1,'Why can''t I sleep at night?');
INSERT INTO question_cards(id,text) VALUES (2,'What''s that smell?');
INSERT INTO question_cards(id,text) VALUES (3,'What is Batman''s guilty pleasure?');
INSERT INTO question_cards(id,text) VALUES (4,'I''m sorry, Professor, but I couldn''t complete my homework because of _.');
INSERT INTO question_cards(id,text) VALUES (5,'What''s that sound?');
INSERT INTO question_cards(id,text) VALUES (6,'Instead of coal, Santa now gives the bad children _.');
INSERT INTO question_cards(id,text) VALUES (7,'Next from J.K. Rowling: Harry Potter and the Chamber of _.');
INSERT INTO question_cards(id,text) VALUES (8,'A romantic, candlelit dinner would be incomplete without _.');
INSERT INTO question_cards(id,text) VALUES (9,'_. Betcha can''t have just one!');
INSERT INTO question_cards(id,text) VALUES (10,'When I am a billionaire, I shall erect a 50-foot statue to commemorate _.');
INSERT INTO question_cards(id,text) VALUES (11,'What will I bring back in time to convince people that I am a powerful wizard?');
INSERT INTO question_cards(id,text) VALUES (12,'Coming to Broadway this season, _: The Musical.');
INSERT INTO question_cards(id,text) VALUES (13,'What''s my secret power?');
INSERT INTO question_cards(id,text) VALUES (14,'But before I kill you, Mr. Bond, I must show you _.');
INSERT INTO question_cards(id,text) VALUES (15,'What never fails to liven up the party?');
INSERT INTO question_cards(id,text) VALUES (16,'The class field trip was completely ruined by _.');
INSERT INTO question_cards(id,text) VALUES (17,'Studies show that lab rats navigate mazes 50% faster after being exposed to _.');
INSERT INTO question_cards(id,text) VALUES (18,'_: Good to the last drop.');
INSERT INTO question_cards(id,text) VALUES (19,'What did Vin Diesel eat for dinner?');
INSERT INTO question_cards(id,text) VALUES (20,'_: kid-tested, mother-approved.');
INSERT INTO question_cards(id,text) VALUES (21,'What gets better with age?');
INSERT INTO question_cards(id,text) VALUES (22,'Dear Abby,I''m having some trouble with _ and would like your advice.');
INSERT INTO question_cards(id,text) VALUES (23,'Maybe she''s born with it. Maybe it''s _.');
INSERT INTO question_cards(id,text) VALUES (24,'Next on ESPN2, the World Series of _.');
INSERT INTO question_cards(id,text) VALUES (25,'During his childhood, Salvador Dali; produced hundreds of paintings of _.');
INSERT INTO question_cards(id,text) VALUES (26,'In 1000 years, when paper money is a distant memory, how will we pay for goods and services?');
INSERT INTO question_cards(id,text) VALUES (27,'The Smithsonian Museum of Natural History has just opened an exhibit on _.');
INSERT INTO question_cards(id,text) VALUES (28,'CNN breaking news! Scientists discover _.');
INSERT INTO question_cards(id,text) VALUES (29,'Coming to Red Lobster this month, _.');
INSERT INTO question_cards(id,text) VALUES (30,'I''m sorry, sir, but your insurance plan doesn''t cover injuries caused by _.');
INSERT INTO question_cards(id,text) VALUES (31,'Oh no! Siri, how do I fix _?');
INSERT INTO question_cards(id,text) VALUES (32,'Run, run, as fast as you can! You can''t catch me, I''m _!');
INSERT INTO question_cards(id,text) VALUES (33,'Then the princess kissed the frog, and all of a sudden the frog was _!');
INSERT INTO question_cards(id,text) VALUES (34,'Well if _ is a crime, then lock me up!');
INSERT INTO question_cards(id,text) VALUES (35,'What are all those whales singing about?');
INSERT INTO question_cards(id,text) VALUES (36,'What''s about to take dance floor to the next level?');
INSERT INTO question_cards(id,text) VALUES (37,'You can''t wait forever. It''s time to talk to your doctor about _.');
INSERT INTO question_cards(id,text) VALUES (38,'My name is Inigo Montoya. You killed my father. Prepare for _.');
INSERT INTO question_cards(id,text) VALUES (39,'From WBEZ Chicago, it''s This American Life. Today on our program, _. Stay with us.');
INSERT INTO question_cards(id,text) VALUES (40,'Why did the chicken cross the road?');
INSERT INTO question_cards(id,text) VALUES (41,'You say tomato, I say _.');
INSERT INTO question_cards(id,text) VALUES (43,'_: not even once.');
INSERT INTO question_cards(id,text) VALUES (44,'Before I got laid off, I never pictured a career in _.');
INSERT INTO question_cards(id,text) VALUES (45,'Coming soon from Pixar: &quot;_&quot;.');
INSERT INTO question_cards(id,text) VALUES (46,'Experts say that without careful management and conservation, _ will disappear within our lifetimes.');
INSERT INTO question_cards(id,text) VALUES (47,'From the producers of Shark Week... Coming this fall, _ Week.');
INSERT INTO question_cards(id,text) VALUES (48,'How did I spend my inheritance?');
INSERT INTO question_cards(id,text) VALUES (49,'I do wish the newspapers hadn''t mentioned _ in grandpa''s obituary.');
INSERT INTO question_cards(id,text) VALUES (50,'I wish it were something simple &mdash; like peanuts or shellfish &mdash; but my doctor tells me I''m actually allergic to _.');
INSERT INTO question_cards(id,text) VALUES (51,'I''m so hungry I could eat _.');
INSERT INTO question_cards(id,text) VALUES (52,'If laughter is the best medicine, the second best is _.');
INSERT INTO question_cards(id,text) VALUES (53,'In Valhalla, it is said that all brave warriors are given _.');
INSERT INTO question_cards(id,text) VALUES (54,'Like Midas reborn, everything she touches turns to _.');
INSERT INTO question_cards(id,text) VALUES (55,'Sweet, I just got a Groupon for _.');
INSERT INTO question_cards(id,text) VALUES (56,'The restaurant was nice, but I was surprised to see _ on the menu.');
INSERT INTO question_cards(id,text) VALUES (57,'Utah is considering the legalization of _.');
INSERT INTO question_cards(id,text) VALUES (58,'What <i>really</i> gave Superman his powers?');
INSERT INTO question_cards(id,text) VALUES (59,'What should I be for Halloween?');
INSERT INTO question_cards(id,text) VALUES (60,'What was one of the rejected flavors for Bertie Bott''s Every Flavour Beans&trade;?');
